### ISSUE TITLE
api bị lỗi

### ISSUE THREAD

**Issue by zeloffDev** [napthedev/nhaccuatui-api-full#1]
error: {code: 1502, message: 'Authorization is expired.'}
status: "error"
time: 1648089168005

**Comment by phongna07** [comment]
Update 1.1.0 đã fix axios luôn update cái authorization

**Comment by zeloffDev** [comment]
tôi đã cài phiên bản mới nhất nhưng status vẫn là error

**Comment by zeloffDev** [comment]
![image](https://user-images.githubusercontent.com/95125148/159919713-4630b70f-3404-44de-a85c-678e5ebe2be7.png)

**Comment by zeloffDev** [comment]
![image](https://user-images.githubusercontent.com/95125148/159919779-ae671f2f-0133-4060-a02e-533304d3a335.png)

**Comment by phongna07** [comment]
Vẫn query bình thường qua react

<img width="540" alt="image" src="https://user-images.githubusercontent.com/74483690/160045428-fd2c7651-9d25-4653-b5b2-225511d6b5c6.png">

<img width="415" alt="image" src="https://user-images.githubusercontent.com/74483690/160045455-05657047-8673-47b7-b876-d2b3e90aa2a6.png">

**Comment by zeloffDev** [comment]
![image](https://user-images.githubusercontent.com/95125148/160048873-9bce32f0-3bc3-43fa-be27-ce5e13c0ed8b.png)

**Comment by zeloffDev** [comment]
![image](https://user-images.githubusercontent.com/95125148/160048921-dddc9b58-5aad-4688-800b-8f107a0b43ff.png)

**Comment by zeloffDev** [comment]
kết nối được nhưng kiểu như token hết hạn vậy

**Comment by tquann286** [comment]
fix được error chưa bạn, hqua mình vẫn query được nhưng nay lại lỗi

**Comment by zeloffDev** [comment]
mình fix được rồi nhé ,nhaccuatuan.surge.sh

**Comment by zeloffDev** [comment]
bạn cập nhật lại ngày ,may mắn thì được , hoặc đổi máy khác xem vào được k, cái nào cũng không được thì lỗi code

**Comment by tquann286** [comment]
vẫn ko được :))
